/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package perpustakaan;

import com.mysql.jdbc.Statement;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import koneksi.koneksi;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Tarigan
 */
public class Form_Registrasi extends javax.swing.JFrame {
    Connection con = null;
    Statement st=null;
    /**
     * Creates new form form_register
     */
    public Form_Registrasi() {
        initComponents();
    }
    
    private void clearscreen(){
        txtname.setText("");
        txtemail.setText("");
        txtuser.setText("");
        txtpas.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtpas = new javax.swing.JPasswordField();
        txtregistrasi = new javax.swing.JButton();
        txtname = new javax.swing.JTextField();
        txtuser = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(310, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(204, 204, 255));
        jLabel2.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SIGN UP");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 11, -1, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Create Your Account");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 47, -1, -1));

        jLabel4.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Name");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 72, -1, -1));

        jLabel5.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Password");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 258, -1, -1));

        jLabel6.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Username");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 201, -1, -1));

        txtpas.setBackground(new java.awt.Color(204, 204, 255));
        txtpas.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel2.add(txtpas, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 281, 239, 28));

        txtregistrasi.setBackground(new java.awt.Color(153, 153, 255));
        txtregistrasi.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txtregistrasi.setText("SIGN UP");
        txtregistrasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtregistrasiActionPerformed(evt);
            }
        });
        jPanel2.add(txtregistrasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 320, 120, 29));

        txtname.setBackground(new java.awt.Color(204, 204, 255));
        txtname.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel2.add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 100, 239, 28));

        txtuser.setBackground(new java.awt.Color(204, 204, 255));
        txtuser.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel2.add(txtuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 224, 239, 28));

        jLabel7.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Email");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 139, -1, -1));

        txtemail.setBackground(new java.awt.Color(204, 204, 255));
        txtemail.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel2.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 162, 239, 28));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/icon/menuutama.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 390));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 0, 530, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtregistrasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtregistrasiActionPerformed
        try {
            if (txtname.getText().equals("")||txtemail.getText().equals("")||txtuser.getText().equals("")||txtpas.getPassword().equals("")){
                JOptionPane.showMessageDialog(this,"Data Tidak Boleh Kosong","Pesan", JOptionPane.ERROR_MESSAGE);
                clearscreen();
            }else{
                Statement statement = (Statement)koneksi.getConnection().createStatement();
                statement.executeUpdate("insert into tb_users VALUES ('"+txtname.getText()+"','"+txtemail.getText()+"','"+txtuser.getText()+"','"+String.valueOf(txtpas.getPassword())+"');");
                statement.close();
                JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
                this.setVisible(false);
                new FormLogin().setVisible(true);
            }
        }catch (HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this,"Akun Sudah Ada","Pesan",JOptionPane.WARNING_MESSAGE);
            clearscreen();
        }
        
    }//GEN-LAST:event_txtregistrasiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Registrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Registrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Registrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Registrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Registrasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtname;
    private javax.swing.JPasswordField txtpas;
    private javax.swing.JButton txtregistrasi;
    private javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables
}
