/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package perpustakaan;

import com.mysql.jdbc.Statement;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import koneksi.koneksi;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tarigan
 */
public class peminjaman extends javax.swing.JFrame {

    /**
     * Creates new form peminjaman
     */
    int x=0;
    
    public peminjaman() {
        initComponents();
        datatable();
        datatable1();
        datatable2();
        tanggal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPinjam = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_peminjaman = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        btnRefresh = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btnEdit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtNim = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        id_buku = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtBuku = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtKembali = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_buku = new javax.swing.JTable();
        txtSearch = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tb_anggota = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        txtSearch1 = new javax.swing.JTextField();
        btnSearch1 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        txtSearch2 = new javax.swing.JTextField();
        btnSearch2 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPinjamActionPerformed(evt);
            }
        });
        getContentPane().add(txtPinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 178, 300, 25));

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(465, 309, -1, -1));

        tb_peminjaman.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "NIM", "Nama", "Kode_Buku", "Nama_Buku", "Tanggal_Pinjam", "Tanggal_Kembali"
            }
        ));
        tb_peminjaman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_peminjamanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_peminjaman);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 338, 609, 115));

        jLabel7.setText(":");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 59, -1, -1));

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        getContentPane().add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 261, -1, -1));

        jLabel8.setText(":");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 90, -1, -1));

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        getContentPane().add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 261, 65, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setText("DATA PEMINJAMAN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, -1, -1));

        jLabel9.setText(":");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 121, -1, -1));

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(548, 309, 71, -1));

        jLabel10.setText(":");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 152, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NIM");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 59, -1, -1));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 261, 71, -1));

        jLabel11.setText(":");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 178, -1, -1));

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 420, 71, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nama");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        txtNim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNimActionPerformed(evt);
            }
        });
        getContentPane().add(txtNim, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 54, 300, 25));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Kode Buku");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 121, -1, -1));
        getContentPane().add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 85, 300, 25));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nama Buku");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 152, -1, -1));
        getContentPane().add(id_buku, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 116, 300, 25));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tanggal Pinjam");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 178, -1, -1));
        getContentPane().add(txtBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 147, 300, 25));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Tanggal Kembali");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 223, -1, -1));

        jLabel13.setText(":");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 223, -1, -1));

        txtKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKembaliActionPerformed(evt);
            }
        });
        getContentPane().add(txtKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 218, 300, 25));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Tabel Data Peminjam");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 315, -1, -1));

        tb_buku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Kode_Buku", "Nama_Buku", "Nama_Pengarang", "Penerbit", "Tahun_Terbit"
            }
        ));
        tb_buku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_bukuMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tb_buku);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 200, 580, 100));
        getContentPane().add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 310, 120, -1));

        tb_anggota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "NIM", "Nama", "Tanggal_Lahir", "Jenis_Kelamin", "Alamat"
            }
        ));
        tb_anggota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_anggotaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tb_anggota);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(637, 60, 580, 97));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Tabel Data Anggota");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 30, -1, -1));
        getContentPane().add(txtSearch1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 30, 146, -1));

        btnSearch1.setText("Search");
        btnSearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearch1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 30, 79, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Tabel Data Buku");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 170, -1, -1));
        getContentPane().add(txtSearch2, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 170, 146, -1));

        btnSearch2.setText("Search");
        btnSearch2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearch2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 170, 79, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/icon/anggota.jpg"))); // NOI18N
        jLabel15.setText("jLabel15");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPinjamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPinjamActionPerformed

    private void txtNimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNimActionPerformed

    private void txtKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKembaliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKembaliActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:

        String NIM = txtNim.getText();
        String Nama = txtNama.getText();
        String Kode_Buku = id_buku.getText();
        String Nama_Buku = txtBuku.getText();
        String Tanggal_Pinjam = txtPinjam.getText();
        String Tanggal_Kembali = txtKembali.getText();
        String Status = "Dipinjam";
        try{
            Statement statement = (Statement)koneksi.getConnection().createStatement();
            statement.executeUpdate("insert into tb_peminjaman VALUES ('"+ NIM +"','"+ Nama +"','"+ Kode_Buku +"','"+ Nama_Buku +"','"+ Tanggal_Pinjam +"','"+ Tanggal_Kembali +"');");
            statement.executeUpdate("update tb_buku SET Status ='"+ Status +"' WHERE Kode_Buku ='"+ Kode_Buku +"';");
            statement.close();
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
            txtNim.setText("");
            txtNama.setText("");
            id_buku.setText("");
            txtBuku.setText("");
            txtPinjam.setText("");
            txtKembali.setText("");
        }catch(Exception t){
            JOptionPane.showMessageDialog(null, "Data Gagal Disimpan");
        }
        datatable();
        datatable1();
        tanggal();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        txtNim.setText("");
        txtNama.setText("");
        id_buku.setText("");
        txtBuku.setText("");
        tanggal();
        txtKembali.setText("");
        txtNim.requestFocus();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
//        tb_peminjaman.setValueAt("", tb_peminjaman.getSelectedRow(),0);
//        tb_peminjaman.setValueAt("", tb_peminjaman.getSelectedRow(),1);
//        tb_peminjaman.setValueAt("", tb_peminjaman.getSelectedRow(),2);
//        tb_peminjaman.setValueAt("", tb_peminjaman.getSelectedRow(),3);
//        tb_peminjaman.setValueAt("", tb_peminjaman.getSelectedRow(),4);
//        tb_peminjaman.setValueAt("", tb_peminjaman.getSelectedRow(),5);

        String NIM = txtNim.getText();
        String Nama = txtNama.getText();
        try{
            Statement statement = (Statement)koneksi.getConnection().createStatement();
            statement.executeUpdate("delete from tb_peminjaman where NIM='"+ NIM +"' OR Nama='"+ Nama +"';");
            JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
            txtNim.setText("");
            txtNama.setText("");
            id_buku.setText("");            
            txtBuku.setText(null);            
            txtKembali.setText("");            
        }catch(Exception t){
            JOptionPane.showMessageDialog(null, "Data Gagal Dihapus");
        }
        datatable();
        tanggal();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        if (btnEdit.getText() == "btnEdit"){
            txtNim.requestFocus();
        }else{
            String NIM = txtNim.getText();
            String Nama = txtNama.getText();
            String Kode_Buku = id_buku.getText();
            String Nama_Buku = txtBuku.getText();
            String Tanggal_Pinjam = txtPinjam.getText();
            String Tanggal_Kembali = txtKembali.getText();
            try{
                Statement statement = (Statement)koneksi.getConnection().createStatement();
                statement.executeUpdate("update tb_peminjaman set NIM='"+ NIM +"',"+"Nama='"+ Nama +"',"+"Kode_Buku='"+ Kode_Buku +"',"+"Nama_Buku='"+ Nama_Buku +"',"+"Tanggal_Pinjam='"+ Tanggal_Pinjam+"',"+"Tanggal_Kembali='"+ Tanggal_Kembali +"'"+ "WHERE NIM='"+ NIM +"' OR Nama='"+ Nama +"'");
                statement.close();
                JOptionPane.showMessageDialog(null, "Data Berhasil Diubah");
                txtNim.setText("");
                txtNama.setText("");
                id_buku.setText("");
                txtBuku.setText("");
                txtKembali.setText("");
            }catch(Exception t){
                JOptionPane.showMessageDialog(null, "Data Gagal Diubah");
            }
            datatable();
            tanggal();
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        try{
            Statement statement = (Statement)koneksi.getConnection().createStatement();
            ResultSet res = statement.executeQuery("select * from tb_peminjaman where "+"NIM like '%"+txtSearch.getText()+"%' OR "+"Nama like '%"+txtSearch.getText()+"%'");
            DefaultTableModel tbl = new DefaultTableModel();
            tbl.addColumn("NIM");
            tbl.addColumn("Nama");
            tbl.addColumn("Kode_Buku");
            tbl.addColumn("Nama_Buku");
            tbl.addColumn("Tanggal_Pinjam");
            tbl.addColumn("Tanggal_Kembali");
            
            tb_peminjaman.setModel(tbl);
            while(res.next()){
                tbl.addRow(new Object[]{
                    res.getString("NIM"),
                    res.getString("Nama"),
                    res.getString("Kode_Buku"),
                    res.getString("Nama_Buku"),
                    res.getString("Tanggal_Pinjam"),
                    res.getString("Tanggal_Kembali"),
                });
            tb_peminjaman.setModel(tbl);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Error");
        }
                
        txtSearch.setText("");
    }//GEN-LAST:event_btnSearchActionPerformed

    private void tb_peminjamanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_peminjamanMouseClicked
        // TODO add your handling code here:
        int i= tb_peminjaman.getSelectedRow();
        if(i == -1){
            return;
        }
        String NIM = (String) tb_peminjaman.getValueAt(i, 0);
        txtNim.setText(NIM);
        String Nama = (String) tb_peminjaman.getValueAt(i, 1);
        txtNama.setText(Nama);
        String Kode_Buku = (String) tb_peminjaman.getValueAt(i, 2);
        id_buku.setText(Kode_Buku);
        String Nama_Buku = (String) tb_peminjaman.getValueAt(i, 3);
        txtBuku.setText(Nama_Buku);
        String Tanggal_Pinjam = (String) tb_peminjaman.getValueAt(i, 4);
        txtPinjam.setText(Tanggal_Pinjam);
        String Tanggal_Kembali = (String) tb_peminjaman.getValueAt(i, 5);
        txtKembali.setText(Tanggal_Kembali);
    }//GEN-LAST:event_tb_peminjamanMouseClicked

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void tb_bukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_bukuMouseClicked
        // TODO add your handling code here:
        int i= tb_buku.getSelectedRow();
        if(i == -1){
            return;
        }
        String Kode_Buku = (String) tb_buku.getValueAt(i, 0);
        id_buku.setText(Kode_Buku);
        String Nama_Buku = (String) tb_buku.getValueAt(i, 1);
        txtBuku.setText(Nama_Buku);
    }//GEN-LAST:event_tb_bukuMouseClicked

    private void tb_anggotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_anggotaMouseClicked
        // TODO add your handling code here:
        int i= tb_anggota.getSelectedRow();
        if(i == -1){
            return;
        }
        String NIM = (String) tb_anggota.getValueAt(i, 0);
        txtNim.setText(NIM);
        String Nama = (String) tb_anggota.getValueAt(i, 1);
        txtNama.setText(Nama);
    }//GEN-LAST:event_tb_anggotaMouseClicked

    private void btnSearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearch1ActionPerformed
        // TODO add your handling code here:
        try{
            Statement statement = (Statement)koneksi.getConnection().createStatement();
            ResultSet res = statement.executeQuery("select * from tb_anggota where "+"NIM like '%"+txtSearch1.getText()+"%' OR "+"Nama like '%"+txtSearch1.getText()+"%'");
            DefaultTableModel tbl = new DefaultTableModel();
            tbl.addColumn("NIM");
            tbl.addColumn("Nama");
            tbl.addColumn("Tanggal_Lahir");
            tbl.addColumn("Jenis_Kelamin");
            tbl.addColumn("Alamat");

            tb_anggota.setModel(tbl);
            while(res.next()){
                tbl.addRow(new Object[]{
                    res.getString("NIM"),
                    res.getString("Nama"),
                    res.getString("Tanggal_Lahir"),
                    res.getString("Jenis_Kelamin"),
                    res.getString("Alamat"),
                });
                tb_anggota.setModel(tbl);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Error");
        }
        txtSearch1.setText("");
    }//GEN-LAST:event_btnSearch1ActionPerformed

    private void btnSearch2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearch2ActionPerformed
        // TODO add your handling code here:
        try{
            Statement statement = (Statement)koneksi.getConnection().createStatement();
            ResultSet res = statement.executeQuery("select * from tb_buku where "+"Kode_Buku like '%"+txtSearch2.getText()+"%' OR "+"Nama_Buku like '%"+txtSearch2.getText()+"%'");
            DefaultTableModel tbl = new DefaultTableModel();
            tbl.addColumn("Kode_Buku");
            tbl.addColumn("Nama_Buku");
            tbl.addColumn("Nama_Pengarang");
            tbl.addColumn("Penerbit");
            tbl.addColumn("Tahun_Terbit");
            
            tb_buku.setModel(tbl);
            while(res.next()){
                tbl.addRow(new Object[]{
                    res.getString("Kode_Buku"),
                    res.getString("Nama_Buku"),
                    res.getString("Nama_Pengarang"),
                    res.getString("Penerbit"),
                    res.getString("Tahun_Terbit"),
                });
            tb_buku.setModel(tbl);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Error");
        }
                
        txtSearch2.setText("");
    }//GEN-LAST:event_btnSearch2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(peminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(peminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(peminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(peminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new peminjaman().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSearch1;
    private javax.swing.JButton btnSearch2;
    private javax.swing.JTextField id_buku;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tb_anggota;
    private javax.swing.JTable tb_buku;
    private javax.swing.JTable tb_peminjaman;
    private javax.swing.JTextField txtBuku;
    private javax.swing.JTextField txtKembali;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNim;
    private javax.swing.JTextField txtPinjam;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSearch1;
    private javax.swing.JTextField txtSearch2;
    // End of variables declaration//GEN-END:variables

    private void datatable() {
        DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("NIM");
        tbl.addColumn("Nama");
        tbl.addColumn("Kode_Buku");
        tbl.addColumn("Nama_Buku");
        tbl.addColumn("Tanggal_Pinjam");
        tbl.addColumn("Tanggal_Kembali");
        tb_peminjaman.setModel(tbl);
        try{
            Statement statement = (Statement) koneksi.getConnection().createStatement();
            ResultSet res = statement.executeQuery("select * from tb_peminjaman");
            while(res.next())
            {
                tbl.addRow(new Object[]{
                    res.getString("NIM"),
                    res.getString("Nama"),
                    res.getString("Kode_Buku"),
                    res.getString("Nama_Buku"),
                    res.getString("Tanggal_Pinjam"),
                    res.getString("Tanggal_Kembali"),
                });
                tb_peminjaman.setModel(tbl);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Gagal");
        }    
    }
    
    private void datatable1() {
        DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("Kode_Buku");
        tbl.addColumn("Nama_Buku");
        tbl.addColumn("Nama_Pengarang");
        tbl.addColumn("Penerbit");
        tbl.addColumn("Tahun_Terbit");
        tbl.addColumn("Status_Buku");
        tb_buku.setModel(tbl);
        try{
            Statement statement = (Statement) koneksi.getConnection().createStatement();
            ResultSet res = statement.executeQuery("select * from tb_buku");
            while(res.next())
            {
                tbl.addRow(new Object[]{
                    res.getString("Kode_Buku"),
                    res.getString("Nama_Buku"),
                    res.getString("Nama_Pengarang"),
                    res.getString("Penerbit"),
                    res.getString("Tahun_Terbit"),
                    res.getString("Status"),
                });
                tb_buku.setModel(tbl);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Gagal");
        }    
    }
    
    private void datatable2() {
        DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("NIM");
        tbl.addColumn("Nama");
        tbl.addColumn("Tanggal_Lahir");
        tbl.addColumn("Jenis_Kelamin");
        tbl.addColumn("Alamat");
        tb_anggota.setModel(tbl);
        try{
            Statement statement = (Statement) koneksi.getConnection().createStatement();
            ResultSet res = statement.executeQuery("select * from tb_anggota");
            while(res.next())
            {
                tbl.addRow(new Object[]{
                    res.getString("NIM"),
                    res.getString("Nama"),
                    res.getString("Tanggal_Lahir"),
                    res.getString("Jenis_Kelamin"),
                    res.getString("Alamat"),
                });
                tb_anggota.setModel(tbl);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Gagal");
        }
    }

    private void tanggal() {
        Date y = new Date();
        SimpleDateFormat s = new SimpleDateFormat("yyyy-MM-dd");
        txtPinjam.setText(s.format(y));
    }
}