/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package perpustakaan;
import com.mysql.jdbc.Statement;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import koneksi.koneksi;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author USER
 */
public class pengembalian extends javax.swing.JFrame {

    /**
     * Creates new form pengembalian
     */
    public pengembalian() {
        initComponents();
        datatable();
        datatable1();
        tanggal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSimpan = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_pengembalian = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtBuku = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_peminjaman = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnSearchDenda = new javax.swing.JButton();
        btnSearchPeminjaman = new javax.swing.JButton();
        txtSearchDenda = new javax.swing.JTextField();
        txtSearchPeminjaman = new javax.swing.JTextField();
        txtTglPinjam = new javax.swing.JTextField();
        btnHitung = new javax.swing.JButton();
        txtTglKembali = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonSimpan.setText("Save");
        jButtonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 305, -1, -1));

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        getContentPane().add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 305, -1, -1));

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 305, -1, -1));

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        getContentPane().add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 305, -1, -1));

        tb_pengembalian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nama", "Nama_Buku", "Tanggal_Pinjam", "Tanggal_Kembali", "Jumlah_Keterlambatan"
            }
        ));
        tb_pengembalian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_pengembalianMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tb_pengembalian);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(413, 227, 609, 116));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nama Anggota :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 14, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tanggal Pinjam :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tanggal Kembali :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));
        getContentPane().add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 174, -1));
        getContentPane().add(txtBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 174, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nama Buku :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 57, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ket : Dikenakan denda apabila pengembalian lebih dari 7 hari !");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 305, -1, -1));

        tb_peminjaman.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "NIM", "Nama", "Kode_Buku", "Nama_Buku", "Tanggal_Pinjam", "Tanggal_Kembali"
            }
        ));
        tb_peminjaman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_peminjamanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_peminjaman);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(413, 54, 609, 115));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Tabel Pengembalian");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(413, 187, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Tabel Peminjaman");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(413, 11, -1, -1));

        btnSearchDenda.setText("Search");
        btnSearchDenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchDendaActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearchDenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 200, -1, -1));

        btnSearchPeminjaman.setText("Search");
        btnSearchPeminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchPeminjamanActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearchPeminjaman, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 20, -1, -1));
        getContentPane().add(txtSearchDenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 200, 160, -1));
        getContentPane().add(txtSearchPeminjaman, new org.netbeans.lib.awtextra.AbsoluteConstraints(779, 20, 160, -1));
        getContentPane().add(txtTglPinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 170, -1));

        btnHitung.setText("Hitung Denda");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });
        getContentPane().add(btnHitung, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 370, -1, -1));
        getContentPane().add(txtTglKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 127, 170, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/icon/anggota.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSimpanActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
        String Nama = txtNama.getText();
        String Buku = txtBuku.getText();
        String Tanggal_Pinjam = txtTglPinjam.getText();
        String Tanggal_Kembali = txtTglKembali.getText();
        String Status = "Tersedia";
        int set = 0;

        try{
            Statement statement = (Statement)koneksi.getConnection().createStatement();
            statement.executeUpdate("insert into tb_pengembalian VALUES ('"+ Nama + "','"+ Buku + "','"+ Tanggal_Pinjam + "','"+ Tanggal_Kembali + "',datediff(Tanggal_Kembali, Tanggal_Pinjam)-7);");
            statement.executeUpdate("delete from tb_peminjaman WHERE Nama='"+ Nama+"' AND Nama_Buku='"+ Buku +"';");
            statement.executeUpdate("update tb_buku SET Status ='"+ Status +"' WHERE Nama_Buku ='"+ Buku +"';");
            ResultSet rs = statement.executeQuery("select Jumlah_Keterlambatan from tb_pengembalian WHERE Nama_Anggota='"+ Nama+"' AND Nama_Buku='"+ Buku +"';");
            try{
                while(rs.next()){
                    if(rs.getInt("Jumlah_Keterlambatan") >= 1 ){
                        JOptionPane.showMessageDialog(null, "Denda");
                    }
                }
            }catch(SQLException ex){
                JOptionPane.showMessageDialog(null, ex);
            }
            statement.close();
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
            txtNama.setText("");
            txtBuku.setText("");
            txtTglPinjam.setText("");
            txtTglKembali.setText("");
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
        datatable();
        datatable1();
        tanggal();
    }//GEN-LAST:event_jButtonSimpanActionPerformed

    private void tb_pengembalianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_pengembalianMouseClicked
        // TODO add your handling code here:
        int i= tb_pengembalian.getSelectedRow();
        if(i == -1){
            return;
        }
        String Nama = (String) tb_pengembalian.getValueAt(i, 0);
        txtNama.setText(Nama);
        String Nama_Buku = (String) tb_pengembalian.getValueAt(i, 1);
        txtBuku.setText(Nama_Buku);
        String Tanggal_Pinjam = (String) tb_pengembalian.getValueAt(i, 2);
        txtTglPinjam.setText(Tanggal_Pinjam);
        String Tanggal_Kembali = (String) tb_pengembalian.getValueAt(i, 3);
        txtTglKembali.setText(Tanggal_Kembali);
    }//GEN-LAST:event_tb_pengembalianMouseClicked

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        if (btnEdit.getText() == "btnEdit"){
            txtNama.requestFocus();
        }else{
            SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
            String Nama = txtNama.getText();
            String Nama_Buku = txtBuku.getText();
            String Tanggal_Pinjam = txtTglPinjam.getText();
            String Tanggal_Kembali = txtTglKembali.getText();
            try{
                Statement statement = (Statement)koneksi.getConnection().createStatement();
                statement.executeUpdate("update tb_pengembalian set Nama_Anggota='"+ Nama +"',Nama_Buku='"+ Nama_Buku +"',Tanggal_Pinjam='"+ Tanggal_Pinjam +"',Tanggal_Kembali='"+ Tanggal_Kembali +"',Jumlah_Keterlambatan = datediff(Tanggal_Kembali, Tanggal_Pinjam)-7 WHERE Nama_Anggota='"+ Nama +"' OR Nama_Buku='"+ Nama_Buku +"'");
                statement.close();
                JOptionPane.showMessageDialog(null, "Data Berhasil Diubah");
                txtNama.setText("");
                txtBuku.setText("");
                txtTglPinjam.setText("");
                txtTglKembali.setText("");
            }catch(SQLException t){
                JOptionPane.showMessageDialog(null, t);
            }
            datatable();
            tanggal();
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        String Nama = txtNama.getText();
        String Nama_Buku = txtBuku.getText();
        try{
            Statement statement = (Statement)koneksi.getConnection().createStatement();
            statement.executeUpdate("delete from tb_pengembalian where Nama_Anggota='"+ Nama +"' OR Nama_Buku='"+ Nama_Buku +"';");
            JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
            txtNama.setText("");
            txtBuku.setText("");
            txtTglPinjam.setText("");
            txtTglKembali.setText("");            
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
        datatable();
        tanggal();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        txtNama.setText("");
        txtBuku.setText("");
        txtTglPinjam.setText("");
        txtTglKembali.setText("");
        txtNama.requestFocus();
        tanggal();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void tb_peminjamanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_peminjamanMouseClicked
        // TODO add your handling code here:
        int i= tb_peminjaman.getSelectedRow();
        if(i == -1){
            return;
        }
        String Nama = (String) tb_peminjaman.getValueAt(i, 1);
        txtNama.setText(Nama);
        String Nama_Buku = (String) tb_peminjaman.getValueAt(i, 3);
        txtBuku.setText(Nama_Buku);
        String Tanggal_Pinjam = (String) tb_peminjaman.getValueAt(i, 4);
        txtTglPinjam.setText(Tanggal_Pinjam);
    }//GEN-LAST:event_tb_peminjamanMouseClicked

    private void btnSearchPeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchPeminjamanActionPerformed
        // TODO add your handling code here:
        try{
            Statement statement = (Statement)koneksi.getConnection().createStatement();
            ResultSet res = statement.executeQuery("select * from tb_peminjaman where "+"NIM like '%"+txtSearchPeminjaman.getText()+"%' OR "+"Nama like '%"+txtSearchPeminjaman.getText()+"%'");
            DefaultTableModel tbl = new DefaultTableModel();
            tbl.addColumn("NIM");
            tbl.addColumn("Nama");
            tbl.addColumn("Kode_Buku");
            tbl.addColumn("Nama_Buku");
            tbl.addColumn("Tanggal_Pinjam");
            tbl.addColumn("Tanggal_Kembali");
            
            tb_peminjaman.setModel(tbl);
            while(res.next()){
                tbl.addRow(new Object[]{
                    res.getString("NIM"),
                    res.getString("Nama"),
                    res.getString("Kode_Buku"),
                    res.getString("Nama_Buku"),
                    res.getString("Tanggal_Pinjam"),
                    res.getString("Tanggal_Kembali"),
                });
            tb_peminjaman.setModel(tbl);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Error");
        }
                
        txtSearchPeminjaman.setText("");
    }//GEN-LAST:event_btnSearchPeminjamanActionPerformed

    private void btnSearchDendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchDendaActionPerformed
        // TODO add your handling code here:
        try{
            Statement statement = (Statement)koneksi.getConnection().createStatement();
            ResultSet res = statement.executeQuery("select * from tb_pengembalian where "+"Nama_Anggota like '%"+txtSearchDenda.getText()+"%' OR "+"Nama like '%"+txtSearchDenda.getText()+"%'");
            DefaultTableModel tbl = new DefaultTableModel();
            tbl.addColumn("Nama");
            tbl.addColumn("Nama_Buku");
            tbl.addColumn("Tanggal_Pinjam");
            tbl.addColumn("Tanggal_Kembali");
            tbl.addColumn("Jumlah_Keterlambatan");
            
            tb_pengembalian.setModel(tbl);
            while(res.next()){
                tbl.addRow(new Object[]{
                    res.getString("Nama"),
                    res.getString("Nama_Buku"),
                    res.getString("Tanggal_Pinjam"),
                    res.getString("Tanggal_Kembali"),
                    res.getString("Jumlah_Keterlambatan"),
                });
            tb_pengembalian.setModel(tbl);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Error");
        }
                
        txtSearchDenda.setText("");
    }//GEN-LAST:event_btnSearchDendaActionPerformed

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        // TODO add your handling code here:
        new denda().setVisible(true);
    }//GEN-LAST:event_btnHitungActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pengembalian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSearchDenda;
    private javax.swing.JButton btnSearchPeminjaman;
    private javax.swing.JButton jButtonSimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tb_peminjaman;
    private javax.swing.JTable tb_pengembalian;
    private javax.swing.JTextField txtBuku;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtSearchDenda;
    private javax.swing.JTextField txtSearchPeminjaman;
    private javax.swing.JTextField txtTglKembali;
    private javax.swing.JTextField txtTglPinjam;
    // End of variables declaration//GEN-END:variables

private void datatable() {
	DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("Nama_Anggota");
        tbl.addColumn("Nama_Buku");
        tbl.addColumn("Tanggal_Pinjam");
        tbl.addColumn("Tanggal_Kembali");
        tbl.addColumn("Jumlah_Keterlambatan");
        tb_pengembalian.setModel(tbl);
        try{
            Statement statement = (Statement) koneksi.getConnection().createStatement();
            ResultSet res = statement.executeQuery("select * from tb_pengembalian");
            while(res.next())
            {
                tbl.addRow(new Object[]{
                    res.getString("Nama_Anggota"),
                    res.getString("Nama_Buku"),
                    res.getString("Tanggal_Pinjam"),
                    res.getString("Tanggal_Kembali"),
                    res.getString("Jumlah_Keterlambatan"),
                });
//                if(res.getInt("Jumlah_Keterlambatan") >= 1){
//                    JOptionPane.showMessageDialog(null, "Denda");
//                }
                tb_pengembalian.setModel(tbl);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Gagal");
        }
    }

private void datatable1() {
        DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("NIM");
        tbl.addColumn("Nama");
        tbl.addColumn("Kode_Buku");
        tbl.addColumn("Nama_Buku");
        tbl.addColumn("Tanggal_Pinjam");
        tbl.addColumn("Tanggal_Kembali");
        tb_peminjaman.setModel(tbl);
        try{
            Statement statement = (Statement) koneksi.getConnection().createStatement();
            ResultSet res = statement.executeQuery("select * from tb_peminjaman");
            while(res.next())
            {
                tbl.addRow(new Object[]{
                    res.getString("NIM"),
                    res.getString("Nama"),
                    res.getString("Kode_Buku"),
                    res.getString("Nama_Buku"),
                    res.getString("Tanggal_Pinjam"),
                    res.getString("Tanggal_Kembali"),
                });
                tb_peminjaman.setModel(tbl);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Gagal");
        }    
    }

private void tanggal() {
        Date y = new Date();
        SimpleDateFormat s = new SimpleDateFormat("yyyy-MM-dd");
        txtTglKembali.setText(s.format(y));
    }
}
